data:
  data_dir: dataset//chest_xray// # Folder containing the dataset
  strength_of_oversampling: 1 # Used for oversampling in the case of deep learning models
  principal_component: 8 # Number of features after PCA

training:
  epochs: 20 # The SVM model receives twice as many epochs as deep learning models (epochs you set)
  batch_size: 32 # Used for training in the case of deep learning models
  learning_rate: 0.001 
  optimizer: adam # Choose one: adam, sgd or rmsprop
  warmup_ratio: 0.1 # Used for faster convergence
  checkpoint_dir: checkpoints/ # Folder containing best models found during training
  device: cuda # Choose one: cuda or cpu
  evaluation_metric: accuracy # Choose one: accuracy, precision, recall, f1 or loss
  best_metric_lower_is_better: false # Choose one: true or false
  early_stopping_metric: loss # Choose one: accuracy, precision, recall, f1 or loss
  earling_stopping_max_no_valid_epochs: 3

ResNet_model:
  stride: [2, 1]
  padding: [3, 1]
  kernel: [7, 3]
  channels_of_color: 3 # RGB
  planes: [64, 128, 256, 512]
  in_features: 512

AlexNet_model:
  stride: [4, 2]
  padding: [2, 1]
  kernel: [8, 5, 3]
  channels_of_color: 3 # RGB
  inplace: true # Choose one: true or false

graph:
  create_dataset_graph: true # Choose one: true or false
  view_dataset_graph: false # Choose one: true or false
  create_model_graph: true # Choose one: true or false
  view_model_graph: false # Choose one: true or false
  create_compare_graph: true # Choose one: true or false
  view_compare_graph: false # Choose one: true or false
  metric_plotted_during_traininig: [accuracy, precision, recall, f1, loss] # Choose: accuracy, precision, recall, f1 and/or loss

classification:
  type: binary # Choose one: binary or ternary